### ISSUE TITLE
Golioth server address dynamic resolution.

### ISSUE THREAD

**Issue by afshin-matin** [golioth/golioth-openthread-demo#7]
Will there be an update for DNS support on OpenThread?
This repository is way behind the other examples.
I hope we get some updates soon.

**Comment by MarkoPura** [comment]
Hey afshin-matin, as a matter of fact, there are some developments regarding OpenThread!
You can check [this branch](https://github.com/golioth/reference-design-template/tree/thread) of our reference-design-template repository. We started experimenting with off-the-shelf Border Routers; we used the [GL-S200](https://www.gl-inet.com/products/gl-s200/) instead of a Raspberry Pi and it works great! If you check out the `thread` branch of reference-design-template, you'll see it has all the functionality, as well as OTA DFU, utilizing the external flash of the two supported boards, Nordic's nRF52840 DK and Adafruit's Feather nRF52840 Express.

**Comment by MarkoPura** [comment]
Hey @afshin-matin, this repository has been updated to the latest [Reference Design Template v2.2.1](https://github.com/golioth/reference-design-template/releases/tag/template_v2.2.1) and, consequently, the [Firmware SDK v0.13.1](https://github.com/golioth/golioth-firmware-sdk/releases/tag/v0.13.1).

DNS support on OpenThread has been in the Zephyr SDK for quite some time and has recently been added to the [Firmware SDK](https://github.com/golioth/golioth-firmware-sdk/commit/8e5650c90e67fc350e4c5827de4bc01d91653e2d).
